apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: golang
  template:
    metadata:
      labels:
        deployment: golang
    spec:
      containers:
      - name: golang
        image: gcr.io/k8s-examples-316720/goapp-example:latest
        ports:
        - containerPort: 3000
---
apiversion: V1
Kind: Service
metadata:
   name: my-Service
spec:
   selector:
      app: golang-deployment
ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    


